name: Deploy Code to AWS Lambda
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python Code
        run: |
          python lambda_handler.py
      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pickle file
          path: model.pkl
      - name: See Files
        run: |
          ls
      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create Zip File
        run: |
          zip -r function.zip . -x "*.git*"
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name FraudCheck --zip-file fileb://function.zip
